[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"
[tool.flit.module]
name = "mdict_query"
[project]
name = "mdict-query"
authors = [{name = "fanyingfx", email = "fanyingfx@outlook.com"}]
readme = "README.md"
dynamic = ["version", "description"]
[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/fanyingfx/mdict-query/issues"
