[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mdict_query"
authors = [{name = "fanyingfx", email = "fanyingfx@outlook.com"}]
readme = "README.md"
dynamic = ["version", "description"]
[tool.flit.module]
name = "mdict_query"
[tool.flit.sdist]
include = ["./"]